### ISSUE TITLE
Works for USD but not for JPY

### ISSUE THREAD

**Issue by siberianguy** [kiyoaki/bitflyer-api-dotnet-client#3]
I'm trying to set up the real-time and it works for BTC_USD but not for BTC_JPY (I receive zero notifications). Do you have an idea why it could be the case? May be BTC_JPY is limited only to Japanese IP addresses?

**Comment by kiyoaki** [comment]
I subscribed RealTime API for BTC USD and BTC JPY. I received both board and ticker without problems.

**Comment by siberianguy** [comment]
Sorry, it was not Bitflyer, it was me being stupid :)
