### ISSUE TITLE
Support to product code argument for market health API

### ISSUE THREAD

**Issue by supermomonga** [kiyoaki/bitflyer-api-dotnet-client#4]
https://lightning.bitflyer.jp/docs?lang=ja#%E5%8F%96%E5%BC%95%E6%89%80%E3%81%AE%E7%8A%B6%E6%85%8B

This API can take the `product_code` argument to specify which market status should be returned, but current `PublicApi.GetHealth()` method can't take that argument.

Could you support `product_code` for `GetHealth` method? or I think I can send a Pull Request.

**Comment by kiyoaki** [comment]
Thanks for your information. I added product_code parameter to GetHealth method.

https://github.com/kiyoaki/bitflyer-api-dotnet-client/commit/490df40c31efdeaee2a42708450097734283eaab

**Comment by supermomonga** [comment]
Thak you!
